apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.1.0
    replicas: 1
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 1Gi
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.1"
    storage:
      type: ephemeral
    tlsSidecar:
      resources:
        requests:
          cpu: 128m
          memory: 64Mi
        limits:
          cpu: 128m
          memory: 64Mi
  zookeeper:
    replicas: 1
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 512Mi
    storage:
      type: ephemeral
    tlsSidecar:
      resources:
        requests:
          cpu: 128m
          memory: 64Mi
        limits:
          cpu: 128m
          memory: 64Mi
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 256Mi
    userOperator:
      resources:
        requests:
          cpu: 250m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 256Mi
    tlsSidecar:
      resources:
        requests:
          cpu: 128m
          memory: 64Mi
        limits:
          cpu: 128m
          memory: 64Mi
